version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gymsysdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
